name: CI workflow
on:
 push: # event as the first event that can trigger the workflow
  branches: [main] #the workflow to start every time somebody pushes to the main branch
 pull_request:  #event similar to the push event you just finished. It should be triggered whenever the user makes a pull request on the main branch.
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20-alpine   
    steps: 
      - name: check out
        uses: actions/checkout@v3 #use the predefined actions/checkout@v3 action to do this
      
      - name: Install dependencies #ci install dependencies specifically designed for CI/CD pipelines in file package-lock.json
        run: | #Unlike npm install, it does not modify the package-lock.json file and installs exactly what's specified there
          npm ci 
 
      - name: Lint with Eslint #Linting is checking your code for syntactical and stylistic issues.
        run: |
          npm run lint 

      - name: Run uni tests with Jest #Jest You will use Jest in this step to unit test the source code. 
        run:  npm test -- --coverage